-- baud_tick_16x.vhd

-- This file contains the 16x baud tick generator. It creates a tick at 16x the baud rate of 115200, giving a 1.8432 MHz tick rate. 
--
-- This equates to a tick approx every 27.1267 clock cycles for a 50 MHz clock. 4096/27.1267 is approx = 151, therefore the 1.8432 MHz tick rate
-- is generated by adding 151 to a 13 bit register, and once the 13th bit goes high, meaning the counter has exceeded 4096, a tick is generated
-- and then the 13th bit is forced low so that the generated tick is only active for one clock period.
--
-- This implementation averages a tick every 27.1258 clock cycles, making an 0.003% error.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity baud_tick_16x is
    port(
        o_tick16x : out std_logic;
        
        clk       : in std_logic;
        rst       : in std_logic
        );
end baud_tick_16x;

architecture rtl of baud_tick_16x is
    
    signal r_counter : unsigned(12 downto 0) := (others => '0');
    signal r_tick    : std_logic := '0';

begin

    baud_tick_16x_proc : process(rst, clk)
    begin
    
        if rst = '0' then --active low
        
            r_counter <= (others => '0');
            r_tick    <= '0';
            
        elsif rising_edge(clk) then
        
            r_counter <= r_counter + x"97"; -- +151
            r_tick    <= r_counter(12);
        
            if r_counter(12) = '1' then
            
                r_counter(12) <= '0';
                
            end if;
            
        end if;
    end process;
    
    o_tick16x <= r_tick;
    
end rtl;